---
- name: Install Apache on RHEL 7
  hosts: all
  tasks:
  - name: Install httpd package
    package:
       name: httpd
       state: present
  - name: Start and enable httpd service
    service:
       name: httpd
       state: started
       enabled: yes
  - name: Enable http port
    firewalld:
       service: http
       permanent: true
       state: enabled
  become: true
  become_method: sudo

