---
- name: This is a hello-world example with sudo
  hosts: all
  tasks:
  - name: Create a file called '/usr/local/etc/testfile.txt' with the content 'hello world'.
    copy: content="hello world\n" dest=/usr/local/etc/testfile.txt
  become: true
  become_method: sudo
