---
- name: Install MariaDB on RHEL 7
  hosts: all
  tasks:
  - name: Install mariadb packages
    package:
       name: "{{ item }}"
       state: present
    with_items:
       - mariadb 
       - mariadb-server 
  - name: Start and enable mariadb service
    service:
       name: mariadb
       state: started
       enabled: yes

  become: true
  become_method: sudo

