---
- name: Install PHP on RHEL 7
  hosts: all
  tasks:
  - name: Install php packages
    package:
       name: "{{ item }}"
       state: present
    with_items:
       - php
       - php-mysql
       - php-mbstring
       - php-gd
  become: true
  become_method: sudo

